### ISSUE TITLE
Error al correr un programa sin instrucción de fin

### ISSUE THREAD

**Issue by regexPattern** [tcorzo/abacus-emulator#2]
Cuando se hace el run de un programa sin fin, por ejemplo, el programa mostrado por defecto, la página se queda colgada y no se puede interactuar con ella hasta que la tab crashea.

https://github.com/user-attachments/assets/523ad5d4-8b7d-4203-a2d4-3309b3b308dc

**Comment by tcorzo** [comment]
Gracias por el issue Carlitos, no sé si lo soluciono hoy por el parcial 😔

Acá el tema es que el emulador avanza por los registros hasta que se llama a la operación de fin de programa.
El hecho de que no haya fin de programa y nunca termine el programa es "realista" (si querés llamarlo así) pero es un gomazo para el usuario obvio.

Así al aire se me ocurren dos cosas:
1. Un timeout, simplemente que un programa no pueda correr por más de, por ejemplo, 10s. Que para todo programa de abacus es más que amplio realmente. Cualquier cosa se puede llegar a modificar por UI
2. Detectar cuando se está por ejecutar un registro inexistente y haltear la ejecución. Esto ahorita no es *tan* facil porque yo cuando le pido un registro al emulador el tipo, si no existe, lo crea y me lo devuelve. Y tampoco puedo revisar si el registro está "vacío" (= 0000) porque, como se vé en el programa de ejemplo, se puede asignar la operación de "carga inmediata" (o cualquier otra) al opcode 0 y eso es una operación 100% válida

**Comment by regexPattern** [comment]
Listo, si la idea era más crear el issue para posibles futuros cambios, capaz para quienes cursen la cátedra en cuatrimestres futuros si decidis mantener la app. Esta muy buena. Mi idea era tener algún tipo de graceful shutdown para casos en los que el código mismo tenga un error.

**Comment by tcorzo** [comment]
@regexPattern Implementados las dos cositas que te mencioné arribe en #3
